### PR TITLE
Added a new DatabaseChoiceListProvider with ja/fr/en translations

### PR DESCRIPTION
**Pull request by tduchateau**
* The new choice list provider is fully configurable: JDBC URL and driver, db name, db table, db column, db username, db password
* Moreover, a fallback mechanism has been added and allows to read a local file containing choices (one per line) if the connection to the database can't be established (for any reason)
* All Messages*.properties have been updated accordingly
* WARNING: the driver class must be manually added to the classpath (either by putting the right JAR in the WEB-INF\lib folder of Jenkins, or by installing one of the Database plugins, such as https://wiki.jenkins-ci.org/display/JENKINS/MySQL+Database+Plugin)

### CODE REVIEW

**Comment by tduchateau** [comment]
Additional notes:

* There is no tests. Shame on me :-(
* I had to comment some `@Override` annotations in order to fix compiling issues. Compiler used in Eclipse: 1.6.
* This one could be a showstopper: I had to upgrade the `org.jenkins-ci.plugins:plugin` from 1.466 to 1.580.1.But because I'm not sure this is the minimal version required, I didn't push the `pom.xml` file
* Finally, I had to explicitely use the latest release of the **maven-hpi-plugin** by adding the following to the `pom.xml` file:

````
<build> 
   <plugins> 
      <plugin> 
         <groupId>org.jenkins-ci.tools</groupId> 
         <artifactId>maven-hpi-plugin</artifactId> 
         <version>1.95</version> 
      </plugin> 
   </plugins> 
</build>
````

File: src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java [hunk 1]
```diff
@@ -0,0 +1,419 @@
...
+				resultat = statement.executeQuery(selectQuery);
+				while(resultat.next()) {
+					resultList.add(resultat.getString(1));				  
+				}
+			}else{
+				LOGGER.log(Level.WARNING,"No result found with the query: " + selectQuery);
+			}
+		}
+		catch (SQLException se) {
+			LOGGER.log(Level.SEVERE,"Unable to access the database: " + dbName + "." + se);
```
Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: Let's use [`Logger.log(Level, String, Throwable)`](http://docs.oracle.com/javase/6/docs/api/java/util/logging/Logger.html#log(java.util.logging.Level,%20java.lang.String,%20java.lang.Throwable)).
It displays also stacktraces.

**Comment by ikedam** [comment]
`mvn eclipse:eclipse` generates build configurations that force to compile with Java 1.5.
That cause compilation errors as annotations (like `@Override`) are introduced in Java1.6.
Uncheck a checkbox like "project specific configuraion" in Project -> Properties -> Java Compiler and you can compile that without errors.

**Comment by ikedam** [comment]
uncheckhere

File: src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java [hunk 2]
```diff
@@ -0,0 +1,419 @@
...
+    private String jdbcUrl;
+    private String dbName;
+    private String dbTable;
+    private String dbColumn;
+    private String dbUsername;
+    private String dbPassword;
+    private String jdbcDriver;
+    private String fallbackFilePath;
+    
+	public String getDbUsername() {
```
Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: Inconsistent indentation.
Please don't use tab letters for indentations. Use only blank letters for that.

Comment (tduchateau) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: Please send me you code style formatter. Much more simpler for me.

Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: I don't think that's a problem with a formatter.
It's generally a bad idea to use both blank characters and tab characters for indentations.
You'd better to configure your Eclipse to display whitespace characters.

If you need a formatter, I recommend you to create a one with following pages.
https://wiki.jenkins-ci.org/display/JENKINS/Governance+Document#GovernanceDocument-CoreCodingConvention
http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

**Comment by ikedam** [comment]
> WARNING: the driver class must be manually added to the classpath (either by putting the right JAR in the WEB-INF\lib folder of Jenkins, or by installing one of the Database plugins, such as https://wiki.jenkins-ci.org/display/JENKINS/MySQL+Database+Plugin)

This can be resolved by integrated with [Database plugin](https://wiki.jenkins-ci.org/display/JENKINS/Database+Plugin).
Though there are too few examples, you can integrate that as a following way (just outline):

1. add an optional dependency to database-plugin 1.1.
    * As 1.1 is the greatest version that works with Jenkins 1.466 targeted by extensible-choice-parameter plugin. 
    * Of course you can upgrade the target Jenkins version and depends to the latest database plugin, but I don't think we need features of database plugin introduced in 1.2.
2. Replace database connaction parameter fields of `DatabaseChoiceList provider` with `Database`.
3. in config.jelly:
    ```
    <f:dropdownDescriptorSelector
    field="database"
    title="${%Database}"
    />
    ```

**Comment by ikedam** [comment]
#9 demonstrates implementation with database plugin.

File: src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java [hunk 3]
```diff
@@ -0,0 +1,419 @@
...
+
+	@Override
+	public List<String> getChoiceList() {
+		List<String> allChoices = performDbQuery();
+		LOGGER.log(Level.CONFIG, "Returned " + allChoices.size() + " entries from the database");
+		return allChoices;
+	}
+	
+	@DataBoundConstructor
+    public DatabaseChoiceListProvider(String userdb, String passworddb, String urldb, String colomndb, String namedb, String tabledb, String driverdb, String fallbackfile)
```
Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: This shouldn't work as Jenkins binds parameters in jelly and parameters in the constructer with their definition name.
(they should be `String dbUsername, String dbPassword, ...)

File: src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java [hunk 4]
```diff
@@ -0,0 +1,419 @@
...
+
+			String tabledb = getDbTable();
+			if (tabledb == null || StringUtils.isEmpty(tabledb)) {
+				LOGGER.log(Level.WARNING,"table database invalid");				
+			}
+			
+			conn = DriverManager.getConnection(urlBase, user, password);
+						
+			// By default, a SELECT * is performed
+			String selectQuery = "select " + colomndb + " from " + namedb + "." + tabledb;
```
Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: This can be a vulnerability.
for example, `columndb = "1; DROP TABLE configuration; SELECT somefield"`

File: src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java [hunk 5]
```diff
@@ -0,0 +1,419 @@
...
+				if (conn != null) {
+					conn.close();
+				}
+			}
+			catch (SQLException se) {
+				LOGGER.log(Level.SEVERE,"Fermeture de connection impossible, SQLException : " + se);
+			}
+		}
+		
+		// If no results are returned, read values from the fallback file if configured
```
Comment (ikedam) [inline src/main/java/jp/ikedam/jenkins/plugins/extensible_choice_parameter/DatabaseChoiceListProvider.java]: This feature can be a vulnerability.
E.g. `fallbackFilepath="/etc/passwd"`

Yes, `FilenameChoiceListProvider` also can be a security vulnerability.

**Comment by MarkEWaite** [comment]
Closing due to unresolved conflicts and no action in 10 years
